Vagrant.configure("2") do |config|
  
  config.vm.define "soufe1" do |soufe1|
    soufe1.vm.box = "centos/stream9"
    soufe1.vm.network :private_network, ip:"192.168.0.20"
    soufe1.vm.provider "virtualbox" do |vb|
      vb.name = "soufe1"
      vb.memory = 1024
      vb.cpus = 2
    end

#Primo provisioning della VM, assegno un hostname 
#e installo ciò che mi serve (in questo caso ansible) ed eseguo un
#playbook 
    
    soufe1.vm.provision "shell", path: "ansible-provisioning.sh"
  end
 

  config.vm.define "soube2" do |soube2|
    soube2.vm.box = "centos/stream9"
    soube2.vm.network :private_network, ip:"192.168.0.21"
    soube2.vm.provider "virtualbox" do |vb|
      vb.name = "soube2"
      vb.memory = 1024
      vb.cpus = 2
    end

    soube2.vm.provision "shell", path: "ansible-provisioning.sh"
  end

end