    - name: Installazione podman
      ansible.builtin.yum:
        name: podman
        state: present

    - name: Controllo servizio podman attivo
      ansible.builtin.systemd:
        name: podman.socket
        enabled: yes
        state: started


