Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream9"

  config.vm.network "private_network", ip: "192.168.0.4",
    virtualbox__intnet: true

  nodes {
    "soufe1" => { ip: "192.168.0.20", memory: 1024, cpus: 2 }
    "soude2" => { ip: "192.168.0.21", memory: 1024, cpus: 2 }
  }

      node.vm.network = "private_network", ip: 192.168.0.4
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024 
        vb.cpus = 1 
      end

end

